### ISSUE TITLE
Epic: Xamarin developers can upgrade to and use the latest .NET SDKs in their existing applications

### ISSUE THREAD

**Issue by maddymontaquila** [dotnet/xamarin#2]
### Summary

Enable developers to target Android, iOS, and macOS in addition to existing platforms such as Windows supported in .NET 6.

### User Stories

User Stories under this Epic: 

##### P0
- [ ] #4 Xamarin developers can acquire and manage mobile .NET SDKs
- [ ] #20 .NET6 Xamarin tooling is supported by VS and VS4M so apps can be compiled, debugged and deployed
- [ ] #6 Xamarin developers will still be able to develop their legacy projects with Visual Studio
- [ ] #16 Xamarin is integrated with common .NET 6 targets and build commands
- [ ] #7 Xamarin developers will share more common developer experiences with .NET developers
- [ ] https://github.com/dotnet/runtime/issues/44654 .NET developers can run iOS and Android apps on emulators and devices in .NET 6
- [x] https://github.com/dotnet/runtime/issues/43078 Developers want to be confident that their apps run successfully when trimmed to avoid debugging trimming related problems at runtime
- [ ] https://github.com/dotnet/runtime/issues/46371 Developers can run diagnostics tooling on their iOS and Android devices

##### P1
- [ ] https://github.com/dotnet/runtime/issues/48761 Mobile developers will experience improved app startup times when targetting .NET 6
- [ ] #15 NuGet packages are updated and available to target .NET 6
- [ ] #9 Xamarin developers can leverage a CLI try-convert tool to move basic Xamarin projects to the new project system
- [ ] https://github.com/dotnet/runtime/issues/44736 Developers can target macOS UI with .NET 6

##### P2
- [ ] #12 Xamarin developers can target Windows with .NET 6
- [ ] https://github.com/dotnet/runtime/issues/46375 Developers can detect performance bottlenecks within their iOS and Android applications
- [ ] https://github.com/dotnet/runtime/issues/46373 Developers can get the most out of profiling their iOS or Android device using dotnet-counters

**Comment by danmoseley** [comment]
@marek-safar we discussed that possibly there may be places in our libraries code (that is not Blazor/Xamarin specific) that will need tuning for eg trading off memory for CPU. Should we have a User Story for that, even if we don't have concrete examples right now? It would be parented here.

**Comment by mairaw** [comment]
I'm cleaning up the .NET 6 project. Can this issue be closed @maddymontaquila or does it need to be updated?
