### ISSUE TITLE
Epic: Xamarin/.NET MAUI developers have improved app performance and share more code with .NET 6

### ISSUE THREAD

**Issue by maddymontaquila** [dotnet/xamarin#21]
## Summary
With Xamarin 6/MAUI, a huge focus is making apps more performant, and making it easier to write cross-platform apps with more shared code and resources.

## User Stories

*P0*
- [x] #10 Xamarin developers can use refactored Xamarin.Core controls for improved performance
- [x] #23 Xamarin developers have maximized resource sharing in their apps

*P1*
- [x] #22 Xamarin developers can maximize code shared across all platforms

*P1*
- [x] #11 Xamarin developers can target all supported platforms from a single project with multi-targeting and have IDE/Tooling support

**Comment by soroshsabz** [comment]
ITNOA

What is real state of this issue? is still active or not?
