### ISSUE TITLE
[Apple] Add support for Mac Catalyst

### ISSUE THREAD

**Issue by rolfbjarne** [dotnet/xamarin#29]
Missing pieces:

* [x] Add new TFM (https://github.com/dotnet/runtime/issues/44882)
* [x] Add runtime packs (https://github.com/dotnet/runtime/issues/47517)
* [x] Add the SDK's implementation and reference pack (https://github.com/xamarin/xamarin-macios/issues/10287)
