### ISSUE TITLE
Epic: Improved development experience for mobile developers to speed up their dev-loop

### ISSUE THREAD

**Issue by maddymontaquila** [dotnet/xamarin#3]
### Summary
Over the past several releases we have delivered incremental improvements to the developer inner loop experience, tooling reliability, and closing the gaps on missing SDK features in Xamarin.Forms that have been frustrating customers.  We have been hindered from making significant advancements in terms of app performance by the original platform renderer design and reliance upon reflection during initialization, so we will be refactoring the Xamarin.Forms native control architecture to eliminate view wrapping. Additionally, using the new project system, we will enable a single project architecture for Xamarin.Forms apps that makes sharing resources across target platforms easier.

Note: These experiences are proposed for .NET 6 and not yet committed.

## User Stories
- [ ] #13 Xamarin developers can use C# Hot Reload while their app is running (P0)
- [ ] #19 Xamarin developers can use XAML Hot Reload to modify their apps UI at runtime (P0)
- [ ] #14 Xamarin developers have faster build and deploy times with Hot Restart (P1)

**Comment by danielmeza** [comment]
We should add Xamarin developers can use C# Hot Reload without debugging.

**Comment by brunck** [comment]
@maddyleger1 please keep things like ensuring that incremental builds on iOS work in mind. 
Any app of any complexity hits this problem, for example just by adding certain NuGet packages (AppCenter was one). This really hurts the current dev-loop.
[Link to issue 3174](https://github.com/xamarin/xamarin-macios/issues/3174)

**Comment by mairaw** [comment]
I'm cleaning up the .NET 6 project. Can this be closed @maddymontaquila?
